# Generated by Django 4.2.8 on 2023-12-12 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='availability',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='services',
        ),
    ]
