# Generated by Django 4.2.8 on 2023-12-12 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0002_remove_venue_availability_remove_venue_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='availability',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venue',
            name='services',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
